# Server
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/vivapg
spring.data.mongodb.database=vivapg

# JWT
jwt.secret=vivapg-secret-key-fatecpg-2026-muito-segura
jwt.expiration=86400000

# CORS
cors.allowed-origins=http://localhost:5173

# APIs Externas
api.ibge.base-url=https://servicodados.ibge.gov.br/api/v3
api.cnes.base-url=https://apidadosabertos.saude.gov.br/v1
api.viacep.base-url=https://viacep.com.br/ws
api.nominatim.base-url=https://nominatim.openstreetmap.org

# Logs
logging.level.br.edu.fatecpg.vivapg=DEBUG
